apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubexray.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kubexray.name" . }}
    helm.sh/chart: {{ include "kubexray.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.yaml: |-
whitelistnamespaces:
  - kube-system
  - two
  - three
  - default
namespacepolicy:
   namespaceone:
     unscanned:
       deployments: scaledown
       statefulsets:  delete
       others: delete
     security:
       deployments: delete
       statefulsets: delete
       others: delete
     license:
       deployments: delete
       statefulsets: delete
       others: delete
   namespacetwo:
     unscanned:
       deployments: scaledown
       statefulsets:  delete
       others: delete
     security:
       deployments: delete
       statefulsets: delete
       others: delete
     license:
       deployments: delete
       statefulsets: delete
       others: delete
defaultpolicy:
   unscanned:
     deployments: scaledown
     statefulsets: delete
     others: delete
   security:
     deployments: delete
     statefulsets: delete
     others: delete
   license:
     deployments: delete
     statefulsets: delete
     others: delete
